### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/easylife
        username: root
        password: 123456
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    type-aliases-package: com.anju.dao.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.anju.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

selfDefined：
    accessKey：oA-CLL4qaJ6NGB4E_3a9Nq4-tb71Cbfjda09X9MG
    secretKey：oA-CLL4qaJ6NGB4E_3a9Nq4-tb71Cbfjda09X9MG