package com.anju.dao.model;

import java.io.Serializable;
import java.util.Date;

public class AppFlick extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flick.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flick.FLICK_USER
     *
     * @mbggenerated
     */
    private String flickUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flick.FLICK_TIME
     *
     * @mbggenerated
     */
    private Date flickTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_flick.FLICK_FILE_ID
     *
     * @mbggenerated
     */
    private String flickFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_flick
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flick.ID
     *
     * @return the value of app_flick.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flick.ID
     *
     * @param id the value for app_flick.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flick.FLICK_USER
     *
     * @return the value of app_flick.FLICK_USER
     *
     * @mbggenerated
     */
    public String getFlickUser() {
        return flickUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flick.FLICK_USER
     *
     * @param flickUser the value for app_flick.FLICK_USER
     *
     * @mbggenerated
     */
    public void setFlickUser(String flickUser) {
        this.flickUser = flickUser == null ? null : flickUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flick.FLICK_TIME
     *
     * @return the value of app_flick.FLICK_TIME
     *
     * @mbggenerated
     */
    public Date getFlickTime() {
        return flickTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flick.FLICK_TIME
     *
     * @param flickTime the value for app_flick.FLICK_TIME
     *
     * @mbggenerated
     */
    public void setFlickTime(Date flickTime) {
        this.flickTime = flickTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_flick.FLICK_FILE_ID
     *
     * @return the value of app_flick.FLICK_FILE_ID
     *
     * @mbggenerated
     */
    public String getFlickFileId() {
        return flickFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_flick.FLICK_FILE_ID
     *
     * @param flickFileId the value for app_flick.FLICK_FILE_ID
     *
     * @mbggenerated
     */
    public void setFlickFileId(String flickFileId) {
        this.flickFileId = flickFileId == null ? null : flickFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flick
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppFlick other = (AppFlick) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFlickUser() == null ? other.getFlickUser() == null : this.getFlickUser().equals(other.getFlickUser()))
            && (this.getFlickTime() == null ? other.getFlickTime() == null : this.getFlickTime().equals(other.getFlickTime()))
            && (this.getFlickFileId() == null ? other.getFlickFileId() == null : this.getFlickFileId().equals(other.getFlickFileId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flick
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFlickUser() == null) ? 0 : getFlickUser().hashCode());
        result = prime * result + ((getFlickTime() == null) ? 0 : getFlickTime().hashCode());
        result = prime * result + ((getFlickFileId() == null) ? 0 : getFlickFileId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_flick
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flickUser=").append(flickUser);
        sb.append(", flickTime=").append(flickTime);
        sb.append(", flickFileId=").append(flickFileId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}