package com.anju.dao.model;

import java.io.Serializable;
import java.util.Date;

public class AppPromo extends BaseEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.FILE_ID
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.PROMO_EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    private Date promoEffectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.PROMO_END_TIME
     *
     * @mbggenerated
     */
    private Date promoEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.PROMO_USER
     *
     * @mbggenerated
     */
    private String promoUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_promo.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_promo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.ID
     *
     * @return the value of app_promo.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.ID
     *
     * @param id the value for app_promo.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.FILE_ID
     *
     * @return the value of app_promo.FILE_ID
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.FILE_ID
     *
     * @param fileId the value for app_promo.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.TYPE
     *
     * @return the value of app_promo.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.TYPE
     *
     * @param type the value for app_promo.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.PROMO_EFFECTIVE_TIME
     *
     * @return the value of app_promo.PROMO_EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    public Date getPromoEffectiveTime() {
        return promoEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.PROMO_EFFECTIVE_TIME
     *
     * @param promoEffectiveTime the value for app_promo.PROMO_EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    public void setPromoEffectiveTime(Date promoEffectiveTime) {
        this.promoEffectiveTime = promoEffectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.PROMO_END_TIME
     *
     * @return the value of app_promo.PROMO_END_TIME
     *
     * @mbggenerated
     */
    public Date getPromoEndTime() {
        return promoEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.PROMO_END_TIME
     *
     * @param promoEndTime the value for app_promo.PROMO_END_TIME
     *
     * @mbggenerated
     */
    public void setPromoEndTime(Date promoEndTime) {
        this.promoEndTime = promoEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.PROMO_USER
     *
     * @return the value of app_promo.PROMO_USER
     *
     * @mbggenerated
     */
    public String getPromoUser() {
        return promoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.PROMO_USER
     *
     * @param promoUser the value for app_promo.PROMO_USER
     *
     * @mbggenerated
     */
    public void setPromoUser(String promoUser) {
        this.promoUser = promoUser == null ? null : promoUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_promo.STATUS
     *
     * @return the value of app_promo.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_promo.STATUS
     *
     * @param status the value for app_promo.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_promo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppPromo other = (AppPromo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPromoEffectiveTime() == null ? other.getPromoEffectiveTime() == null : this.getPromoEffectiveTime().equals(other.getPromoEffectiveTime()))
            && (this.getPromoEndTime() == null ? other.getPromoEndTime() == null : this.getPromoEndTime().equals(other.getPromoEndTime()))
            && (this.getPromoUser() == null ? other.getPromoUser() == null : this.getPromoUser().equals(other.getPromoUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_promo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPromoEffectiveTime() == null) ? 0 : getPromoEffectiveTime().hashCode());
        result = prime * result + ((getPromoEndTime() == null) ? 0 : getPromoEndTime().hashCode());
        result = prime * result + ((getPromoUser() == null) ? 0 : getPromoUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_promo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileId=").append(fileId);
        sb.append(", type=").append(type);
        sb.append(", promoEffectiveTime=").append(promoEffectiveTime);
        sb.append(", promoEndTime=").append(promoEndTime);
        sb.append(", promoUser=").append(promoUser);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}